-- MySQL Script generated by MySQL Workbench
-- Sat 25 Sep 2021 09:48:39 PM -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema database_payment_system
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `database_payment_system` ;

-- -----------------------------------------------------
-- Schema database_payment_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_payment_system` ;
USE `database_payment_system` ;

-- -----------------------------------------------------
-- Table `database_payment_system`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_payment_system`.`customers` ;

CREATE TABLE IF NOT EXISTS `database_payment_system`.`customers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `lastname` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `code` INT NOT NULL,
  `grade` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `state` VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code` (`code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `database_payment_system`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_payment_system`.`orders` ;

CREATE TABLE IF NOT EXISTS `database_payment_system`.`orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `method` VARCHAR(15) NOT NULL,
  `code` INT UNSIGNED NOT NULL,
  `total_price` FLOAT UNSIGNED NULL DEFAULT 0.0,
  `customer_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `customer_id`),
  INDEX `fk_orders_customers_idx` (`customer_id` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `database_payment_system`.`shipments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_payment_system`.`shipments` ;

CREATE TABLE IF NOT EXISTS `database_payment_system`.`shipments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `price` FLOAT UNSIGNED NOT NULL,
  `product` VARCHAR(45) NOT NULL,
  `amount` INT NULL DEFAULT 0,
  `orders_id` INT UNSIGNED NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `orders_id`, `customer_id`),
  INDEX `fk_shipments_orders1_idx` (`orders_id` ASC, `customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_shipments_orders1`
    FOREIGN KEY (`orders_id` , `customer_id`)
    REFERENCES `database_payment_system`.`orders` (`id` , `customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
